### PR TITLE
Update package.json  Because error using with svelte

### PR DESCRIPTION
**Pull request by van1164**
Error when used with svelte...

### CODE REVIEW

**Comment by timgesekus** [comment]
I got the same problem. Is there a workaround until this is fixed?

**Comment by van1164** [comment]
> I got the same problem. Is there a workaround until this is fixed?

Have you tried the method I modified?

**Comment by partyvaper** [comment]
Hey, any progress with this?

**Comment by lukeed** [comment]
What's the problem? No one has specified anything yet. 

An "exports" map entry for a file shouldn't point to a directory.

**Comment by van1164** [comment]
I don't know what's the problem, but my commit solve the problem

**Comment by partyvaper** [comment]
Can you check if `"default":"./dist/index.js"` also works?

**Pull request closed without merging**
